"""product_sku_not_nullable

Revision ID: 6c16905349d9
Revises: d79096c6c126
Create Date: 2026-03-21 00:21:34.011750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c16905349d9'
down_revision = 'd79096c6c126'
branch_labels = None
depends_on = None


def upgrade():
    # Disable FK checks for SQLite batch alter
    conn = op.get_bind()
    conn.execute(sa.text('PRAGMA foreign_keys=OFF'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    conn.execute(sa.text('PRAGMA foreign_keys=ON'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('sku',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
